### ISSUE TITLE
should we rename bundle.js?

### ISSUE THREAD

**Issue by JohnMcLear** [dcdc-io/node-gp#4]
Should we output nodegp-bundle.js or something more descriptive instead so when it's included in another project we're not expecting bundle.js to be copy/pasta'd

**Comment by benbenbenbenbenben** [comment]
No reason why not.

Although if people are including other libraries they should be doing their own bundling instead of using our requires "index.js" file like we do to output a bundle (`browserify -p tinyify ./index.js -o ./browser/nodegp-bundle.js`)

I'll add a note.
