### ISSUE TITLE
TypeError: GlobalPlatform is not a constructor

### ISSUE THREAD

**Issue by DNThomas** [dcdc-io/node-gp#7]
C:\Users\DuncanThomas\Desktop\nodegp_test>node index.js
C:\Users\DuncanThomas\Desktop\nodegp_test\index.js:11
        const gpcard = new GlobalPlatform(transceive)
                       ^

TypeError: GlobalPlatform is not a constructor
    at Device.event.device.on.event (C:\Users\DuncanThomas\Desktop\nodegp_test\index.js:11:24)
    at Device.emit (events.js:198:13)
    at C:\Users\DuncanThomas\node_modules\smartcard\lib\Device.js:50:27

Getting this when trying the fully working example. Using (for my sins) Win10 / Node v10.16.3

**Comment by benbenbenbenbenben** [comment]
Apologies, that was an issue with the default exports. It's fixed now.
